### PR TITLE
Ignore messages without a rule ID

### LINKED ISSUE #40: Error with ignored file
The first item in my report looks like this.

```json
  {
    "filePath": "/Users/rpmcelbd/code/front-end/.github/workflows/web-ci.yaml",
    "messages": [
      {
        "fatal": false,
        "severity": 1,
        "message": "File ignored by default.  Use a negated ignore pattern (like \"--ignore-pattern '!<relative/path/to/filename>'\") to override."
      }
    ],
    "suppressedMessages": [],
    "errorCount": 0,
    "fatalErrorCount": 0,
    "warningCount": 1,
    "fixableErrorCount": 0,
    "fixableWarningCount": 0,
    "usedDeprecatedRules": []
  }
```

## Actual

I'm getting the following error.

```
Empty value for parameter 'output.annotations[0].end_line': undefined
```

## Expected

It should skip this warning because the file is ignored. It doesn't matter that there's no `end_line`. It should probably ignore anything that doesn't have a `ruleId`.

### PR DESCRIPTION
**Pull request by pmcelhaney**
fixes #40

### CODE REVIEW

**Comment by ataylorme** [comment]
@pmcelhaney I am making updates in a v2 refactor #44. I added this update there. Can you test `ataylorme/eslint-annotate-action@v2`

Also if you provide an ESLint JSON file with an example of a missing ruleId I will add a unit test for it.

**Comment by pmcelhaney** [comment]
Here's an example of a message that does not have a rule ID.

```
[
  {
    "filePath": "/path/to/ignored-me.js",
    "messages": [
      {
        "fatal": false,
        "severity": 1,
        "message": "File ignored because of a matching ignore pattern. Use \"--no-ignore\" to override."
      }
    ],
    "suppressedMessages": [],
    "errorCount": 0,
    "fatalErrorCount": 0,
    "warningCount": 1,
    "fixableErrorCount": 0,
    "fixableWarningCount": 0,
    "usedDeprecatedRules": [
      { "ruleId": "no-buffer-constructor", "replacedBy": [] }
    ]
  }
]
```

To recreate:

1. Create a file called `ignore-me.js`
2. Add `ignore-me.js` to your `.eslintignore`
3. Run `eslint ignore-me.js --format json`

I would test your branch, but I don't have any repos that are using the action right now. I ended up creating my own custom formatter and running ESLint directly as part of a larger workflow.

**Comment by ataylorme** [comment]
Thank you for following up @pmcelhaney. I'm going to close this PR since `v2` of the Action incorporates this change.

I will say though that I think there may be some exploring to do with how you are triggering ESLInt to generate the report in the first place.

Ignored files shouldn't be making it into the report in general with `eslint .`. However, if you specify a path to lint that includes ignored files they will be added to the report. `eslint **/*.js` as an example. See [this comment](https://github.com/eslint/eslint/issues/5623#issuecomment-209789397)

**Comment by pmcelhaney** [comment]
I’m using the changed files action to get a list of changed *.js and *.ts files and pass the list to ESLint.

**Comment by ataylorme** [comment]
@pmcelhaney I think that is an issue as you are explicitly passing files to the longer that are normally ignored.

The v2 version of this Action has an option to only check files changes in the PR. Please test that instead

**Pull request closed without merging**
